#!/usr/bin/env python
"""Per-AI launchers as THIN shims: a Start/Talk .bat pair, written into the
pack, that call the parameterized launcher chain with -Persona and -Port.

The alternative was a forked copy of Start-Enigma.ps1 per AI, which is how a
launcher chain rots: the copies drift, and the AI whose copy is stale is the
one that stops booting. Everything these shims know is the pack directory and
the port -- every decision (which checkpoint, which organs, whose memory
store, who owns the port) stays in the one .ps1 they call.

    python make_persona_launchers.py personas\\atlas

Refuses the DEFAULT persona: Enigma's launchers already exist at the repo root
and are the ones the Desktop shortcuts point at. Refuses a pack with no `port`
field for the same reason the field exists -- a second AI silently inheriting
8000 is a collision with whoever is serving, discovered at boot.
"""

from __future__ import annotations

import sys
from pathlib import Path

from enigma_engine.core.persona import PACK_MANIFEST, Persona

ROOT = Path(__file__).resolve().parent

START_BAT = "Start.bat"
TALK_BAT = "Talk.bat"


def _start_bat(persona: Persona, pack: Path) -> str:
    return (
        "@echo off\r\n"
        f"REM Start {persona.name} -- the shared launcher, this pack, her own port.\r\n"
        f"REM Generated by make_persona_launchers.py; edit the pack, not this file.\r\n"
        f'powershell -NoProfile -ExecutionPolicy Bypass -File "{ROOT / "Start-Enigma.ps1"}"'
        f' -Persona "{pack}" -Port {persona.port}\r\n'
    )


def _talk_bat(persona: Persona, pack: Path) -> str:
    return (
        "@echo off\r\n"
        f"REM Talk to {persona.name} -- start her if she is not up, then open her\r\n"
        "REM window on her own port. Generated by make_persona_launchers.py.\r\n"
        f'call "%~dp0{START_BAT}"\r\n'
        "if errorlevel 1 exit /b 1\r\n"
        f'start "" py -3.12 "{ROOT / "enigma_window.py"}" --persona "{pack}"'
        f' --url http://127.0.0.1:{persona.port}/\r\n'
    )


def write_launchers(pack_dir: Path) -> tuple[Persona, list[Path]]:
    """Write the pair into `pack_dir`; return whose they are and what was written.

    The pack is loaded rather than read: the port rules, the name rules and
    the is_default answer are the loader's, so a pack these shims accept is
    one serve will accept too."""
    pack = Path(pack_dir).resolve()
    persona = Persona.load(pack)
    if persona.is_default:
        raise SystemExit(
            f"persona pack {pack} IS Enigma -- her launchers are the repo's own "
            "(Talk to Enigma.bat / Enigma Tray.bat / Stop Enigma.bat)"
        )
    if persona.port is None:
        raise SystemExit(
            f"persona pack {pack} declares no port; add a \"port\" to "
            f"{PACK_MANIFEST} (1024-65535, not 8000 or 8123) -- a second AI "
            "inheriting the default port collides with whoever is serving there"
        )
    written = []
    for name, text in ((START_BAT, _start_bat(persona, pack)),
                       (TALK_BAT, _talk_bat(persona, pack))):
        path = pack / name
        # newline="" -- the CRLF the .bat text already carries is written as
        # it stands; cmd.exe is the one consumer that reads a bare LF file
        # wrong on the lines that matter.
        with open(path, "w", encoding="ascii", newline="") as fh:
            fh.write(text)
        written.append(path)
    return persona, written


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print("usage: python make_persona_launchers.py <pack-dir>")
        return 1
    persona, written = write_launchers(Path(argv[0]))
    for path in written:
        print(f"wrote {path}")
    print(f"{persona.name} launches on port {persona.port}; "
          f"double-click {TALK_BAT} in the pack to talk to her")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
