"""
Tokenizer v2 pre-tokenization tests.

Two jobs, in order of importance:

1. V1 MUST NOT MOVE.  The served v8 model was trained against the live
   4718-token vocab and its exact v1 tokenization.  Any change to v1
   encode/decode output silently corrupts every prompt the model sees.
   ``test_v1_*`` pins that behaviour with hardcoded IDs generated from
   the code as it stood BEFORE v2 existed.  If one of those fails, v2
   work has leaked into v1 -- fix v2, never the expected IDs.

2. v2 does what it claims: leading spaces attached to words, one token
   per digit, and lossless round-tripping.

Non-ASCII fixtures are written as escape sequences (\\u00e9 etc.) rather
than literal characters so this file stays pure ASCII on disk and does
not trip the repo hygiene gates in tests/test_repo_hygiene.py.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from enigma_engine.core.advanced_tokenizer import AdvancedBPETokenizer
from enigma_engine.core.bpe_tokenizer import BPETokenizer
from enigma_engine.core.pretokenize import (
    PRETOKENIZER_V1,
    PRETOKENIZER_V2,
    normalize_pretokenizer,
    pretokenize_v2,
)
from enigma_engine.core.tokenizer import get_tokenizer

REPO_ROOT = Path(__file__).resolve().parent.parent
LIVE_VOCAB = REPO_ROOT / "enigma_engine" / "vocab_model" / "bpe_vocab.json"


# ---------------------------------------------------------------------------
# 1. v1 immutability -- the critical gate
# ---------------------------------------------------------------------------

# Generated by running the tokenizer BEFORE the v2 change landed.
# add_special_tokens=False so BOS/EOS placement is not part of the pin.
V1_PINNED_ENCODINGS: dict[str, list[int]] = {
    "The quick brown fox jumps over the lazy dog.": [
        2826, 44, 349, 293, 119, 44, 1693, 122, 44, 722, 132, 44, 118, 364,
        124, 127, 44, 1111, 44, 383, 44, 417, 134, 133, 44, 112, 401, 58,
    ],
    "Enigma is a 182M parameter model trained from scratch.": [
        81, 604, 115, 571, 44, 388, 44, 109, 44, 1182, 62, 89, 44, 536, 1644,
        277, 44, 685, 44, 309, 456, 113, 112, 44, 395, 121, 44, 127, 3200,
        294, 332, 58,
    ],
    "Numbers: 1000 2500 42 7": [
        2681, 277, 127, 70, 44, 61, 2234, 60, 44, 62, 65, 2234, 44, 64, 62, 44, 67,
    ],
}


@pytest.fixture(scope="module")
def live_tokenizer():
    """The real served tokenizer, loaded from the real vocab file."""
    if not LIVE_VOCAB.exists():
        pytest.skip(f"live vocab not present: {LIVE_VOCAB}")
    return get_tokenizer("bpe")


@pytest.mark.parametrize("text", sorted(V1_PINNED_ENCODINGS))
def test_v1_live_encoding_is_bit_identical(live_tokenizer, text):
    """The live tokenizer still produces the exact pre-v2 token IDs."""
    expected = V1_PINNED_ENCODINGS[text]
    assert live_tokenizer.encode(text, add_special_tokens=False) == expected, (
        "v1 tokenization changed -- the served v8 model depends on these exact "
        "IDs. Something in the v2 work leaked into the v1 path."
    )


@pytest.mark.parametrize("text", sorted(V1_PINNED_ENCODINGS))
def test_v1_live_round_trip(live_tokenizer, text):
    ids = live_tokenizer.encode(text, add_special_tokens=False)
    assert live_tokenizer.decode(ids, skip_special_tokens=True) == text


def test_v1_live_tokenizer_reports_v1(live_tokenizer):
    """Absence of the key must resolve to v1, not to a default of v2."""
    assert live_tokenizer.pretokenizer_version == PRETOKENIZER_V1


def test_live_vocab_file_has_no_pretokenizer_key():
    """The on-disk live vocab must stay untouched by the v2 work.

    Absence of "pretokenizer" is what makes the file v1, so writing the
    key here -- even with the value "v1" -- would be a behaviour change
    dressed up as a no-op.
    """
    if not LIVE_VOCAB.exists():
        pytest.skip(f"live vocab not present: {LIVE_VOCAB}")
    data = json.loads(LIVE_VOCAB.read_text(encoding="utf-8"))
    assert "pretokenizer" not in data
    assert set(data) == {"token_to_id", "merges", "special_tokens", "use_utf8_bytes"}
    assert data["use_utf8_bytes"] is False


def test_v1_trainer_pre_tokenizer_unchanged():
    """v1's trainer split still drops whitespace exactly as it always did."""
    tok = BPETokenizer()
    assert tok.pretokenizer_version == PRETOKENIZER_V1
    assert tok._pre_tokenize("the cat sat") == ["the", "cat", "sat"]


# ---------------------------------------------------------------------------
# 2. v2 pre-tokenizer properties
# ---------------------------------------------------------------------------

LOSSLESS_CASES = [
    "",
    " ",
    "the cat",
    "a  b",
    "hi  ",
    "   leading and trailing   ",
    "line one\nline two\r\n\ttabbed",
    "don't can't we've I'll he'd it's",
    "snake_case_name and __dunder__ and path/to/file_name.py",
    "1000 2500 42 7 3.14159",
    "x=1; y+=2 // comment {a: [b]}",
    "caf\u00e9 na\u00efve r\u00e9sum\u00e9 stra\u00dfe",  # accented latin
    "\u65e5\u672c\u8a9e\u306e\u30c6\u30ad\u30b9\u30c8",  # CJK
    "\u041f\u0440\u0438\u0432\u0435\u0442 \u043c\u0438\u0440",  # Cyrillic
    "emoji \U0001F600\U0001F44D\U0001F680 end",
    "mixed \U0001F600 \u65e5\u672c 123 _x_ !!",
    "\u0660\u0661\u0662 arabic-indic digits",
    "trailing newline\n",
    "\n\n\n",
]


@pytest.mark.parametrize("text", LOSSLESS_CASES)
def test_v2_pretokenize_is_lossless(text):
    """Concatenating the pieces must reproduce the input exactly.

    This is the contract v2 decode rests on: no piece may be dropped,
    stripped, or normalised.
    """
    assert "".join(pretokenize_v2(text)) == text


def test_v2_pretokenize_lossless_codepoint_sweep():
    """No character class hole anywhere in the BMP.

    re.findall silently SKIPS characters no alternative matches, so a
    gap in the pattern loses text with no error. The spec's original
    pattern had exactly this bug for "_". Sweep to prove there are no
    others.
    """
    bad: list[str] = []
    codepoints = list(range(0x00, 0x3200)) + [0x4E00, 0x1F600, 0x1F44D, 0x10FFFF]
    for cp in codepoints:
        ch = chr(cp)
        for ctx in (ch, "a" + ch + "b", " " + ch, ch + "1"):
            if "".join(pretokenize_v2(ctx)) != ctx:
                bad.append(f"U+{cp:04X} in {ctx!r}")
                break
    assert not bad, f"pretokenize_v2 dropped characters: {bad[:20]}"


def test_v2_attaches_leading_space_to_words():
    assert pretokenize_v2("the cat") == ["the", " cat"]
    assert pretokenize_v2("a b c") == ["a", " b", " c"]


def test_v2_emits_no_bare_space_between_words():
    """The whole point: a separator space rides along with its word."""
    pieces = pretokenize_v2("one two three four")
    assert " " not in pieces


@pytest.mark.parametrize(
    "text,expected",
    [
        ("1000", ["1", "0", "0", "0"]),
        ("2500", ["2", "5", "0", "0"]),
        ("42", ["4", "2"]),
        ("7", ["7"]),
        (" 42", [" 4", "2"]),
        (" 7", [" 7"]),
    ],
)
def test_v2_digits_split_one_at_a_time(text, expected):
    """v1 was position dependent (1000 -> ['1','00','0'] but
    2500 -> ['2','5','00']); v2 must always be one digit per unit."""
    assert pretokenize_v2(text) == expected


def test_v2_contractions_stay_whole():
    assert pretokenize_v2("don't") == ["don", "'t"]
    assert pretokenize_v2("we've") == ["we", "'ve"]
    assert pretokenize_v2("I'll") == ["I", "'ll"]


def test_v2_underscore_is_preserved():
    """Regression: the original v2 pattern matched no alternative for
    "_", so re.findall dropped it and "snake_case" became
    ["snake", "case"]."""
    pieces = pretokenize_v2("snake_case")
    assert "".join(pieces) == "snake_case"
    assert "_" in "".join(pieces)


def test_normalize_pretokenizer_defaults_and_rejects():
    assert normalize_pretokenizer(None) == PRETOKENIZER_V1
    assert normalize_pretokenizer("") == PRETOKENIZER_V1
    assert normalize_pretokenizer("v1") == PRETOKENIZER_V1
    assert normalize_pretokenizer("v2") == PRETOKENIZER_V2
    with pytest.raises(ValueError):
        normalize_pretokenizer("v3")


# ---------------------------------------------------------------------------
# 3. v2 end to end (tiny training run)
# ---------------------------------------------------------------------------

TINY_CORPUS = (
    "The quick brown fox jumps over the lazy dog. The dog was not amused. "
    "She sells sea shells by the sea shore, and the shells she sells are sea shells. "
    "In the year 1000 there were 2500 people, and by 42 years later only 7 remained. "
    "Enigma is a model that learns from data. The model learns and the data grows. "
    "Training a model on data makes the model better at the task it was trained for. "
) * 12

HELD_OUT = (
    "The model learns from the data, and 1000 people saw 42 dogs by the shore.\n"
    "New line\ttab  double space and a caf\u00e9."
)


@pytest.fixture(scope="module")
def v2_trained(tmp_path_factory):
    """A tiny v2 vocab trained once and reused across the v2 tests."""
    out = tmp_path_factory.mktemp("tok_v2") / "v2_vocab.json"
    tok = BPETokenizer(pretokenizer=PRETOKENIZER_V2)
    tok.train([TINY_CORPUS], vocab_size=400, min_frequency=2, verbose=False)
    tok.save(out)
    return tok, out


def test_v2_training_reports_v2(v2_trained):
    tok, _ = v2_trained
    assert tok.pretokenizer_version == PRETOKENIZER_V2


def test_v2_round_trip_is_lossless_trainer_class(v2_trained):
    tok, _ = v2_trained
    ids = tok.encode(HELD_OUT, add_special_tokens=False)
    assert tok.decode(ids, skip_special_tokens=True) == HELD_OUT


def test_v2_round_trip_is_lossless_runtime_class(v2_trained):
    _, path = v2_trained
    runtime = AdvancedBPETokenizer(vocab_file=path)
    ids = runtime.encode(HELD_OUT, add_special_tokens=False)
    assert runtime.decode(ids, skip_special_tokens=True) == HELD_OUT


def test_v2_learned_a_leading_space_token(v2_trained):
    """v1 learned 0% leading-space merges because its trainer never saw
    a space. v2 must actually merge them."""
    tok, _ = v2_trained
    leading = [t for t in tok.token_to_id if len(t) > 1 and t.startswith(" ")]
    assert leading, "no merge with an attached leading space was learned"


def test_v2_emits_no_end_of_word_marker(v2_trained):
    """v2 deliberately drops </w>: the leading space already carries the
    boundary, and </w>-to-space substitution would break lossless
    decode."""
    tok, _ = v2_trained
    assert "</w>" not in tok.token_to_id
    assert not any("</w>" in a or "</w>" in b for a, b in tok.merges)


def test_v2_keeps_digits_single(v2_trained):
    """No merge may glue two digits together."""
    tok, _ = v2_trained
    multi_digit = [t for t in tok.token_to_id if sum(c.isdigit() for c in t) > 1]
    assert not multi_digit, f"multi-digit tokens learned: {multi_digit[:10]}"


def test_v2_rarely_emits_a_bare_space_token(v2_trained):
    """A bare " " must exist in the base vocab (any whitespace run has to
    be encodable), but it should almost never be EMITTED, because the
    separator now rides on the following word."""
    tok, _ = v2_trained
    assert " " in tok.token_to_id, "base vocab must still cover a literal space"
    ids = tok.encode(HELD_OUT, add_special_tokens=False)
    space_id = tok.token_to_id[" "]
    bare = sum(1 for i in ids if i == space_id) / len(ids)
    assert bare < 0.05, f"bare-space tokens still {bare:.1%} of the stream"


def test_v2_save_load_preserves_version(v2_trained):
    _, path = v2_trained
    raw = json.loads(path.read_text(encoding="utf-8"))
    assert raw["pretokenizer"] == PRETOKENIZER_V2

    reloaded = BPETokenizer(vocab_file=path)
    assert reloaded.pretokenizer_version == PRETOKENIZER_V2
    assert reloaded.decode(reloaded.encode(HELD_OUT, add_special_tokens=False), True) == HELD_OUT

    runtime = AdvancedBPETokenizer(vocab_file=path)
    assert runtime.pretokenizer_version == PRETOKENIZER_V2


def test_v1_save_omits_pretokenizer_key(tmp_path):
    """A v1 save must keep the legacy file shape byte for byte."""
    tok = BPETokenizer()
    tok.train(["hello world hello there world"], vocab_size=300, min_frequency=1, verbose=False)
    out = tmp_path / "v1_vocab.json"
    tok.save(out)
    raw = json.loads(out.read_text(encoding="utf-8"))
    assert "pretokenizer" not in raw
    assert BPETokenizer(vocab_file=out).pretokenizer_version == PRETOKENIZER_V1


def test_v2_special_tokens_survive_round_trip(v2_trained):
    """Tags must be carved out BEFORE the v2 pattern runs, or they get
    shredded into punctuation and letter runs."""
    tok, _ = v2_trained
    text = "before <think> hidden reasoning </think> after"
    ids = tok.encode(text, add_special_tokens=False)
    assert tok.special_tokens["<think>"] in ids
    assert tok.special_tokens["</think>"] in ids
    assert tok.decode(ids, skip_special_tokens=False) == text


def test_v2_special_tokens_survive_runtime_encode(v2_trained):
    _, path = v2_trained
    runtime = AdvancedBPETokenizer(vocab_file=path)
    text = "ask <search> weather today </search> done"
    ids = runtime.encode(text, add_special_tokens=False)
    assert runtime.special_tokens["<search>"] in ids
    assert runtime.special_tokens["</search>"] in ids
    assert runtime.decode(ids, skip_special_tokens=False) == text


def test_v2_pre_tokenize_routes_through_shared_module(v2_trained):
    """Trainer and runtime must both use pretokenize_v2 -- the v1 wart
    was two inline regexes that disagreed."""
    tok, path = v2_trained
    runtime = AdvancedBPETokenizer(vocab_file=path)
    plain = "the cat sat on 42 mats"
    assert tok._pre_tokenize(plain) == pretokenize_v2(plain)
    assert runtime._pre_tokenize_v2(plain) == pretokenize_v2(plain)


# ---------------------------------------------------------------------------
# 4. v2 beats v1 on the same corpus
# ---------------------------------------------------------------------------

# A few KB of ordinary English prose, so the chars/token comparison is
# decisive rather than a tiny-corpus artefact.
PROSE = (
    "It is a truth universally acknowledged that a single man in possession of a good "
    "fortune must be in want of a wife. However little known the feelings or views of "
    "such a man may be on his first entering a neighbourhood, this truth is so well "
    "fixed in the minds of the surrounding families that he is considered as the "
    "rightful property of some one or other of their daughters. My dear Mr Bennet, "
    "said his lady to him one day, have you heard that Netherfield Park is let at last? "
    "Mr Bennet replied that he had not. But it is, returned she, for Mrs Long has just "
    "been here and she told me all about it. Mr Bennet made no answer. Do you not want "
    "to know who has taken it? cried his wife impatiently. You want to tell me and I "
    "have no objection to hearing it. This was invitation enough. Why my dear you must "
    "know Mrs Long says that Netherfield is taken by a young man of large fortune from "
    "the north of England, that he came down on Monday in a chaise and four to see the "
    "place and was so much delighted with it that he agreed with Mr Morris immediately. "
    "He is to take possession before Michaelmas and some of his servants are to be in "
    "the house by the end of next week. What is his name? Bingley. Is he married or "
    "single? Oh single my dear to be sure. A single man of large fortune, four or five "
    "thousand a year. What a fine thing for our girls. How so? How can it affect them? "
) * 3

PROSE_HELD_OUT = (
    "My dear Mr Bennet, said his lady, a single man of good fortune must be in want of "
    "a wife, and the surrounding families know it well before the end of next week."
)


def _chars_per_token(tokenizer, text: str) -> float:
    return len(text) / len(tokenizer.encode(text, add_special_tokens=False))


def test_v2_is_more_efficient_than_v1(tmp_path):
    """Same corpus, same target vocab size, same runtime class -- the
    only difference is the pre-tokenizer.

    Measured with AdvancedBPETokenizer (the class that actually encodes
    for the model) rather than BPETokenizer, because v1's trainer-side
    encode silently DROPS whitespace, which would flatter v1 with a
    chars/token figure for text it cannot reconstruct.
    """
    v1_path = tmp_path / "v1.json"
    v2_path = tmp_path / "v2.json"

    t1 = BPETokenizer()
    t1.train([PROSE], vocab_size=1000, min_frequency=2, verbose=False)
    t1.save(v1_path)

    t2 = BPETokenizer(pretokenizer=PRETOKENIZER_V2)
    t2.train([PROSE], vocab_size=1000, min_frequency=2, verbose=False)
    t2.save(v2_path)

    r1 = AdvancedBPETokenizer(vocab_file=v1_path)
    r2 = AdvancedBPETokenizer(vocab_file=v2_path)

    cpt1 = _chars_per_token(r1, PROSE_HELD_OUT)
    cpt2 = _chars_per_token(r2, PROSE_HELD_OUT)

    assert cpt2 > cpt1, f"v2 ({cpt2:.3f} chars/token) did not beat v1 ({cpt1:.3f})"
    # Only v2 can actually reconstruct the text it encoded.
    assert r2.decode(r2.encode(PROSE_HELD_OUT, add_special_tokens=False), True) == PROSE_HELD_OUT
